export default {
  content: ["./public/index.html", "./src/**/*.{js,jsx,ts,tsx}"],
  theme: {
    extend: {
      colors: {
        primary: "#002F2D",
        "primary-container": "#0D4744",
        "primary-fixed": "#b7ede8",
        "primary-fixed-dim": "#9cd0cc",
        "on-primary": "#ffffff",
        "on-primary-container": "#81b4b0",
        "on-primary-fixed": "#00201e",
        "on-primary-fixed-variant": "#184f4b",
        "inverse-primary": "#9cd0cc",
        accent: "#FFB95F",
        "on-accent": "#2A1700",
        background: "#FAF9F8",
        surface: "#FAF9F8",
        "surface-bright": "#faf9f8",
        "surface-dim": "#dadad9",
        "surface-variant": "#e3e2e1",
        "surface-tint": "#336763",
        "surface-low": "#F4F3F2",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#F4F3F2",
        "surface-container": "#EEEEED",
        "surface-container-high": "#E9E8E7",
        "surface-container-highest": "#E3E2E1",
        foreground: "#1A1C1C",
        "on-surface": "#1a1c1c",
        "on-surface-variant": "#404847",
        "on-background": "#1a1c1c",
        "inverse-surface": "#2f3130",
        "inverse-on-surface": "#f1f0f0",
        secondary: "#5F5E5E",
        "secondary-container": "#e2dfde",
        "secondary-fixed": "#e5e2e1",
        "secondary-fixed-dim": "#c8c6c5",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#636262",
        "on-secondary-fixed": "#1c1b1b",
        "on-secondary-fixed-variant": "#474746",
        tertiary: "#3e2400",
        "tertiary-container": "#5b3800",
        "tertiary-fixed": "#ffddb8",
        "tertiary-fixed-dim": "#FFB95F",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#ee9900",
        "on-tertiary-fixed": "#2a1700",
        "on-tertiary-fixed-variant": "#653e00",
        outline: "#707978",
        "outline-variant": "#BFC8C7",
        error: "#BA1A1A",
        "error-container": "#ffdad6",
        "on-error": "#ffffff",
        "on-error-container": "#93000a",
      },
      fontFamily: {
        headline: ["Noto Serif", "serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
        mono: ["Geist Mono", "monospace"],
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      animation: {
        "pulse-slow": "pulse 3s cubic-bezier(0.4, 0, 0.6, 1) infinite",
        shimmer: "shimmer 2s infinite linear",
      },
      keyframes: {
        shimmer: {
          "0%": { backgroundPosition: "-200% 0" },
          "100%": { backgroundPosition: "200% 0" },
        },
      },
    },
  },
  plugins: [],
};
